name: Format

on:
    pull_request:
        branches: [main]

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            # 1️⃣ Checkout PR branch
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            # 2️⃣ Set up Node
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            # 3️⃣ Install dependencies
            - run: npm ci

            # 4️⃣ Run Prettier
            - run: npm run format

            # 5️⃣ Commit any formatting changes
            - name: Commit formatting changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply frontend formatting
                  branch: ${{ github.head_ref }}
